### ISSUE TITLE
milliseconds always 0

### ISSUE THREAD

**Issue by phieber** [adafruit/Adafruit-GPS-Library#49]
It seem that GPS.milliseconds is always 0.

**Comment by tdicola** [comment]
Yeah for anyone that stumbles on this in the future, check the datasheet for the GPS module and you can see an example of its GGA and RMC outputs, like:
```
$GPGGA,064951.000,2307.1256,N,12016.4438,E,1,8,0.95,39.9,M,17.8,M,,*65
```
Time is the first value after the GGA identifier, and it only outputs to the second accuracy.  The library should support parsing to milliseconds if there's a more accurate module in the future, but for now it's just down to seconds from the module.
